name: delivery
description: Delivery app using clean architecture.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_shimmer: ^2.1.2
  freezed_annotation: ^2.2.0
  go_router: ^6.0.7
  intl: ^0.17.0
  riverpod_annotation: ^1.2.1
  rxdart: ^0.27.7
  sembast: ^3.4.0+6
  sembast_web: ^2.1.0+4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_generator: ^1.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

assets:
  - assets/img/
